# Generated by Django 4.2.6 on 2024-03-06 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_order_status'),
        ('order_history', '0002_alter_orderhistory_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_history', to='order.order'),
        ),
    ]
