# Generated by Django 4.2.6 on 2024-04-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_history', '0003_alter_orderhistory_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
