# Generated by Django 4.2.6 on 2024-04-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_history', '0004_orderhistory_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='is_created_mail',
            field=models.BooleanField(default=False),
        ),
    ]
