# Generated by Django 4.2.6 on 2024-04-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiodocument',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
