# Generated by Django 4.2.6 on 2024-01-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_category_created_at_alter_category_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code_name',
            field=models.CharField(default='code', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
