# Generated by Django 4.1.13 on 2024-05-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_category_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('SERVICE', 'SERVICE'), ('PRODUCT', 'PRODUCT')], max_length=255),
        ),
    ]
