# Generated by Django 4.1.13 on 2024-05-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='updated_by',
        ),
    ]
