# Generated by Django 4.2.6 on 2024-01-23 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code_name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('name_with_type', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code_name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('name_with_type', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code_name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('name_with_type', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='address.district')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='provide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='address.provide'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.district')),
                ('provide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.provide')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.ward')),
            ],
        ),
    ]
