# Generated by Django 4.2.6 on 2024-01-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ward',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
