# Generated by Django 4.2.6 on 2024-01-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_alter_district_code_name_alter_ward_code_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='id',
        ),
        migrations.RemoveField(
            model_name='provide',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='id',
        ),
        migrations.AlterField(
            model_name='district',
            name='code',
            field=models.IntegerField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='provide',
            name='code',
            field=models.IntegerField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ward',
            name='code',
            field=models.IntegerField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
