# Generated by Django 4.2.6 on 2024-01-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_remove_district_id_remove_provide_id_remove_ward_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='provide',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ward',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
