# Generated by Django 4.2.6 on 2024-01-23 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_alter_district_code_alter_provide_code_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Provide',
            new_name='Province',
        ),
    ]
