# Generated by Django 4.2.6 on 2024-01-28 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_rename_provide_province'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='provide',
            new_name='province',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='provide',
            new_name='province',
        ),
    ]
