# Generated by Django 4.2.6 on 2024-03-19 07:48

import backend.custom_middleware
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedemocomment',
            name='user',
            field=models.ForeignKey(default=backend.custom_middleware.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
