# Generated by Django 4.2.6 on 2024-04-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_alter_imagedemocomment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedemo',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imagedemocomment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
