# Generated by Django 4.1.13 on 2024-05-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_imagedemo_is_deleted_imagedemocomment_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagedemo',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='imagedemo',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='imagedemocomment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='imagedemocomment',
            name='updated_by',
        ),
    ]
