# Generated by Django 4.2.6 on 2024-01-21 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0011_alter_studio_email_alter_studio_phone_and_more'),
        ('user', '0002_user_studio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='asset/avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='studio',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='studio.studio'),
        ),
    ]
