# Generated by Django 4.2.6 on 2024-03-08 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0013_studio_address_delete_studioaddress'),
        ('user', '0006_user_date_of_birth_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='studio',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='studio.studio'),
        ),
    ]
