# Generated by Django 4.2.6 on 2024-03-19 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0015_studio_account_number_studio_bank_bin'),
        ('user', '0008_user_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='studio',
            new_name='own_studio',
        ),
        migrations.AddField(
            model_name='user',
            name='word_for_studio',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to='studio.studio'),
        ),
    ]
