# Generated by Django 4.2.6 on 2024-03-19 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0015_studio_account_number_studio_bank_bin'),
        ('user', '0009_rename_studio_user_own_studio_user_word_for_studio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='word_for_studio',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to='studio.studio'),
        ),
    ]
