# Generated by Django 4.2.6 on 2024-04-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain_forum', '0002_replypicture_delete_replyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='replypicture',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
