# Generated by Django 4.1.13 on 2024-05-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complain_forum', '0003_reply_is_deleted_replypicture_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='replypicture',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='replypicture',
            name='updated_by',
        ),
    ]
