# Generated by Django 4.2.2 on 2023-11-24 14:34

import backend.custom_middleware
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0010_rename_name_studio_friendly_name'),
        ('item', '0004_alter_item_created_at_alter_item_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='studio',
            field=models.ForeignKey(default=backend.custom_middleware.get_current_studio, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='studio.studio'),
        ),
    ]
