# Generated by Django 4.2.2 on 2023-11-24 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_item_studio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_public',
        ),
    ]
