# Generated by Django 4.2.2 on 2023-11-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_remove_item_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='picture',
            field=models.ImageField(null=True, upload_to='item'),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('DRAFT', 'DRAFT')], default='DRAFT', max_length=255),
        ),
    ]
