# Generated by Django 4.2.2 on 2023-12-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_item_picture_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='star',
            field=models.FloatField(default=5),
        ),
    ]
