# Generated by Django 4.2.6 on 2024-01-22 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_remove_item_picture_item_pictures_variation_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='pictures',
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('DRAFT', 'DRAFT')], default='ACTIVE', max_length=255),
        ),
        migrations.CreateModel(
            name='ItemPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='item')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='item.item')),
            ],
        ),
    ]
