# Generated by Django 4.2.6 on 2024-01-22 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_remove_item_pictures_alter_item_status_itempicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempicture',
            name='image',
        ),
        migrations.AddField(
            model_name='itempicture',
            name='item',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='item.item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itempicture',
            name='picture',
            field=models.ImageField(upload_to='item'),
        ),
    ]
