# Generated by Django 4.2.6 on 2024-01-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_alter_variation_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='value',
            field=models.ManyToManyField(related_name='value', to='item.optionvalue'),
        ),
    ]
