# Generated by Django 4.2.6 on 2024-01-24 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_alter_variation_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option', to='item.item'),
        ),
        migrations.AlterField(
            model_name='optionvalue',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_value', to='item.option'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='value',
            field=models.ManyToManyField(related_name='variation', to='item.optionvalue'),
        ),
    ]
