# Generated by Django 4.1.13 on 2024-05-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0017_item_is_deleted_option_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('SERVICE', 'SERVICE'), ('SERVICE_PACK', 'SERVICE_PACK'), ('PRODUCT', 'PRODUCT'), ('ACCESSORY', 'ACCESSORY')], max_length=255),
        ),
    ]
