# Generated by Django 4.1.13 on 2024-05-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0018_alter_item_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='item',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='option',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='option',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='optionvalue',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='optionvalue',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='updated_by',
        ),
    ]
