# Generated by Django 4.2.2 on 2023-11-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studio',
            name='user',
        ),
        migrations.AddField(
            model_name='studio',
            name='email',
            field=models.EmailField(default='email@email.com', max_length=255),
        ),
    ]
