# Generated by Django 4.2.2 on 2023-11-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_remove_studio_user_studio_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
