# Generated by Django 4.2.2 on 2023-11-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_alter_studio_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studioaddress',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
