# Generated by Django 4.2.2 on 2023-11-24 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_alter_document_created_at_alter_document_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.studio'),
        ),
    ]
