# Generated by Django 4.2.2 on 2023-11-24 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0007_alter_document_studio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studioaddress',
            old_name='country',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='studioaddress',
            old_name='state',
            new_name='ward',
        ),
    ]
