# Generated by Django 4.2.2 on 2023-11-24 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0008_rename_country_studioaddress_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='code_name',
            field=models.CharField(default='test', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studioaddress',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='studio.studio'),
        ),
    ]
