# Generated by Django 4.2.6 on 2024-01-21 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0010_rename_name_studio_friendly_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='studio',
            name='phone',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='studio',
            name='tax_code',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
