# Generated by Django 4.2.6 on 2024-01-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0011_alter_studio_email_alter_studio_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatars/'),
        ),
    ]
