# Generated by Django 4.2.6 on 2024-01-23 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_alter_district_code_name_alter_ward_code_name'),
        ('studio', '0012_studio_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address'),
        ),
        migrations.DeleteModel(
            name='StudioAddress',
        ),
    ]
