# Generated by Django 4.2.6 on 2024-03-09 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0013_studio_address_delete_studioaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
