# Generated by Django 4.2.6 on 2024-03-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0014_delete_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studio',
            name='bank_bin',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
