# Generated by Django 4.2.6 on 2024-04-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0015_studio_account_number_studio_bank_bin'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='number_order_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studio',
            name='number_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studio',
            name='star',
            field=models.FloatField(default=0),
        ),
    ]
