# Generated by Django 4.2.6 on 2024-04-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0016_studio_number_order_completed_studio_number_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='star',
            field=models.FloatField(default=5),
        ),
    ]
