# Generated by Django 4.2.6 on 2024-04-11 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0016_studio_account_name'),
        ('studio', '0017_alter_studio_star'),
    ]

    operations = [
    ]
