# Generated by Django 4.2.6 on 2024-04-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0018_merge_0016_studio_account_name_0017_alter_studio_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='account_balance',
            field=models.IntegerField(default=0),
        ),
    ]
