# Generated by Django 4.2.6 on 2024-04-17 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0019_studio_account_balance'),
        ('studio', '0019_studio_type'),
    ]

    operations = [
    ]
