# Generated by Django 4.1.13 on 2024-05-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0021_studio_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studio',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='updated_by',
        ),
    ]
