# Generated by Django 4.2.2 on 2023-12-06 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0010_rename_name_studio_friendly_name'),
        ('order', '0004_alter_orderitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='studio',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='studio.studio'),
            preserve_default=False,
        ),
    ]
