# Generated by Django 4.2.6 on 2023-12-13 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0010_rename_name_studio_friendly_name'),
        ('order', '0005_order_studio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='studio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='studio.studio'),
        ),
    ]
