# Generated by Django 4.2.6 on 2024-02-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_orderitem_variation_alter_orderitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transportion_price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
