# Generated by Django 4.2.6 on 2024-02-26 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_transportion_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='transportion_price',
            new_name='transportation_price',
        ),
    ]
