# Generated by Django 4.2.6 on 2024-02-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_rename_transportion_price_order_transportation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_remain',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
