# Generated by Django 4.2.6 on 2024-02-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_amount_remain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount_remain',
        ),
        migrations.AddField(
            model_name='order',
            name='amount_created',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
