# Generated by Django 4.2.6 on 2024-03-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_remove_order_amount_remain_order_amount_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'ORDERED'), ('IN_PROCESS', 'IN_PROCESS'), ('SHIPPPING', 'SHIPPPING'), ('COMPLETED', 'COMPLETED'), ('CANCELED', 'CANCELED')], default='ORDERED', max_length=255),
        ),
    ]
