# Generated by Django 4.2.6 on 2024-04-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='done_payment',
            field=models.BooleanField(default=False),
        ),
    ]
