# Generated by Django 4.2.2 on 2023-11-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='description',
            field=models.CharField(default=None, max_length=511, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.CharField(default=None, max_length=511, null=True),
        ),
    ]
