# Generated by Django 4.2.2 on 2023-11-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0005_alter_permission_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permission',
            field=models.ManyToManyField(null=True, to='role.permission'),
        ),
    ]
