# Generated by Django 4.2.2 on 2023-11-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0006_alter_role_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permission',
            field=models.ManyToManyField(to='role.permission'),
        ),
    ]
