# Generated by Django 4.1.13 on 2024-05-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0008_permission_is_deleted_role_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='role',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='role',
            name='updated_by',
        ),
    ]
