# Generated by Django 4.2.6 on 2024-04-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_media_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='title',
            field=models.TextField(default='title'),
            preserve_default=False,
        ),
    ]
