# Generated by Django 4.2.6 on 2024-04-06 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_order_address'),
        ('complain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='complain', to='order.order'),
        ),
    ]
