# Generated by Django 4.2.6 on 2024-04-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0002_alter_complain_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complainpicture',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
