# Generated by Django 4.1.13 on 2024-05-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0003_complain_is_deleted_complainpicture_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='complain',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='complainpicture',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='complainpicture',
            name='updated_by',
        ),
    ]
