# Generated by Django 4.1.13 on 2024-05-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_rate_is_deleted_ratepicture_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='ratepicture',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ratepicture',
            name='updated_by',
        ),
    ]
