# Generated by Django 4.2.6 on 2024-02-26 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank_tran_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='number_attemp_in_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_attemp_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='vn_order_infor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='vn_pay_tran_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
