# Generated by Django 4.2.6 on 2024-04-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='vn_pay_TxnRef',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PAID', 'PAID'), ('DESTROYED', 'DESTROYED'), ('REFUND', 'REFUND')], default='PENDING', max_length=20),
        ),
    ]
